name: mongodb-cluster

services:
  rs0as:
    command: --config /etc/mongo/mongod.conf
    image: mongo:7.0.9
    ports:
    - 8000:27018
    networks:
    - mongo
    volumes:
    - ./data/rs0as/db:/data/db
    - ./config/rs0.conf:/etc/mongo/mongod.conf

  rs0bs:
    command: --config /etc/mongo/mongod.conf
    image: mongo:7.0.9
    ports:
    - 8001:27018
    networks:
    - mongo
    volumes:
    - ./data/rs0bs/db:/data/db
    - ./config/rs0.conf:/etc/mongo/mongod.conf

  rs0cs:
    command: --config /etc/mongo/mongod.conf
    image: mongo:7.0.9
    ports:
    - 8002:27018
    networks:
    - mongo
    volumes:
    - ./data/rs0cs/db:/data/db
    - ./config/rs0.conf:/etc/mongo/mongod.conf

networks:
  mongo:
    name: mongo
