name: mongodb-cluster

services:
# replica set 0: rs0
  rs0as:
    command: --config /etc/mongo/mongod.conf
    image: mongo:7.0.9
    ports:
    - 8000:27018
    networks:
    - mongo
    volumes:
    - ./data/rs0as/db:/data/db
    - ./config/rs0.conf:/etc/mongo/mongod.conf

  rs0bs:
    command: --config /etc/mongo/mongod.conf
    image: mongo:7.0.9
    ports:
    - 8001:27018
    networks:
    - mongo
    volumes:
    - ./data/rs0bs/db:/data/db
    - ./config/rs0.conf:/etc/mongo/mongod.conf

  rs0cs:
    command: --config /etc/mongo/mongod.conf
    image: mongo:7.0.9
    ports:
    - 8002:27018
    networks:
    - mongo
    volumes:
    - ./data/rs0cs/db:/data/db
    - ./config/rs0.conf:/etc/mongo/mongod.conf

# replica set 1: rs1
  rs1as:
    command: --config /etc/mongo/mongod.conf
    image: mongo:7.0.9
    ports:
    - 8003:27018
    networks:
    - mongo
    volumes:
    - ./data/rs1as/db:/data/db
    - ./config/rs1.conf:/etc/mongo/mongod.conf

  rs1bs:
    command: --config /etc/mongo/mongod.conf
    image: mongo:7.0.9
    ports:
    - 8004:27018
    networks:
    - mongo
    volumes:
    - ./data/rs1bs/db:/data/db
    - ./config/rs1.conf:/etc/mongo/mongod.conf

  rs1cs:
    command: --config /etc/mongo/mongod.conf
    image: mongo:7.0.9
    ports:
    - 8005:27018
    networks:
    - mongo
    volumes:
    - ./data/rs1cs/db:/data/db
    - ./config/rs1.conf:/etc/mongo/mongod.conf

# config server replica set: cfg
  cfga:
    command: --config /etc/mongo/mongod.conf
    image: mongo:7.0.9
    ports:
    - 8006:27019
    networks:
    - mongo
    volumes:
    - ./data/cfga/db:/data/db
    - ./config/cfg.conf:/etc/mongo/mongod.conf

  cfgb:
    command: --config /etc/mongo/mongod.conf
    image: mongo:7.0.9
    ports:
    - 8007:27019
    networks:
    - mongo
    volumes:
    - ./data/cfgb/db:/data/db
    - ./config/cfg.conf:/etc/mongo/mongod.conf

  cfgc:
    command: --config /etc/mongo/mongod.conf
    image: mongo:7.0.9
    ports:
    - 8008:27019
    networks:
    - mongo
    volumes:
    - ./data/cfgc/db:/data/db
    - ./config/cfg.conf:/etc/mongo/mongod.conf

  # mongos query router
  mongos:
    command: mongos --config /etc/mongo/mongos.conf
    image: mongo:7.0.9
    ports:
    - 27017:27017
    networks:
    - mongo
    volumes:
    - ./data/mongos/db:/data/db
    - ./config/mongos.conf:/etc/mongo/mongos.conf

networks:
  mongo:
    name: mongo
